include: package:lints/recommended.yaml

analyzer:
  exclude:
    - 'out/**'
    - 'tool/icon_generator/**'
  language:
    strict-casts: true

linter:
  rules:
    - directives_ordering
    - unawaited_futures
