analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - 'out/**'
    - 'tool/icon_generator/**'

linter:
  rules:
    - prefer_single_quotes
    - type_annotate_public_apis
    - unawaited_futures
