/*
 * Copyright 2017 The Chromium Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
package io.flutter.sdk;

import com.intellij.openapi.util.SystemInfo;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

public class FlutterSdkUtilsTest {
  @Test
  public void parseFlutterSdkPath() {
    final String content = """
      # Generated by pub on 2017-07-07 12:58:30.541312.
      async:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/async-1.13.3/lib/
      charcode:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.1/lib/
      collection:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/collection-1.14.2/lib/
      flutter:file:///Users/devoncarew/projects/flutter/flutter/packages/flutter/lib/
      http:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/http-0.11.3+13/lib/
      http_parser:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/http_parser-3.1.1/lib/
      intl:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/intl-0.14.0/lib/
      meta:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/meta-1.0.5/lib/
      path:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/path-1.4.2/lib/
      sky_engine:../../flutter/flutter/bin/cache/pkg/sky_engine/lib/
      source_span:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/source_span-1.4.0/lib/
      stack_trace:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/stack_trace-1.7.4/lib/
      string_scanner:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/string_scanner-1.0.2/lib/
      typed_data:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/typed_data-1.1.3/lib/
      vector_math:file:///Users/devoncarew/.pub-cache/hosted/pub.dartlang.org/vector_math-2.0.5/lib/
      flutter_sunflower:lib/
      """;

    String result = FlutterSdkUtil.parseFlutterSdkPath(content);
    if (result != null && SystemInfo.isWindows) {
      result = result.replaceAll("\\\\", "/");
    }
    assertEquals("/Users/devoncarew/projects/flutter/flutter", result);
  }

  @Test
  public void flutterScriptName() {
    if (SystemInfo.isWindows) {
      assertEquals("flutter.bat", FlutterSdkUtil.flutterScriptName());
    }
    else {
      assertEquals("flutter", FlutterSdkUtil.flutterScriptName());
    }
  }

  @Test
  public void parseFlutterSdkPath_invalid() {
    assertNull(FlutterSdkUtil.parseFlutterSdkPath(""));
    assertNull(FlutterSdkUtil.parseFlutterSdkPath("# comment only"));
    assertNull(FlutterSdkUtil.parseFlutterSdkPath("foo:bar"));
  }

  @Test
  public void parseFlutterSdkPath_userHome() {
    // Verify we can parse a path that uses ~
    // Actually the parser expects file: URIs often, let's check the implementation.
    // parseFlutterSdkPath expects "flutter:file:///..."

    final String content = "flutter:file:///Users/user/flutter/packages/flutter/lib/";
    String result = FlutterSdkUtil.parseFlutterSdkPath(content);
    if (SystemInfo.isWindows) {
      // On Windows it might produce different separators, but the input here is
      // unix-style URI
      // The impl uses Urls.parseEncoded
      // Let's assume the method handles basic URI parsing.
      // If result is null, it failed.
      if (result != null) {
        result = result.replaceAll("\\\\", "/");
        assertEquals("/Users/user/flutter", result);
      }
    }
    else {
      assertEquals("/Users/user/flutter", result);
    }
  }
}
