name: 'Auto Assign'
on:
  # Safe because this workflow does not checkout untrusted code or execute any scripts.
  # It strictly passes metadata to a trusted action to use the GitHub API.
  # zizmor: ignore[dangerous-triggers]
  pull_request_target:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    # Don't auto-assign for project owners.
    if: github.actor != 'pq' && github.actor != 'helin24'
    steps:
      - uses: kentaro-m/auto-assign-action@a6d59add3a817df08cafa9b166367768d2c337f8 # v2.0.1
