name: presubmit
on: [push]
jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      - name set java home
        run: echo "$Env:JAVA_HOME=%JAVA_HOME_11_X64%" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: windows UNIT_TEST_BOT
        run: ./tool/github.bat
        shell: cmd
