name: presubmit
on: [push]
jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      - name: windows UNIT_TEST_BOT
        run: ./tool/github.bat
        env:
          JAVA_HOME: ${{ $JAVA_HOME_11_X64 }}
        shell: cmd
